language: python
python: "2.7"
# command to install dependencies
install: "pip install -r requirements/test.txt --use-mirrors"
# command to run tests
script: ./django_printer/manage.py test publication --settings=django_printer.settings.test
